markdown: rdiscount
markdown: redcarpet
permalink: /:year/:month/:day/:title/
url: http://lovelife.github.io
author: lovelife
syntax-highlighting:
  enabled : true
  
safe: true
paginate: 16
auto: true

